In [1]:
import numpy as np

In [2]:
np.random.seed(42)

In [10]:
def monte_carplo_pi(num_points):
    points = np.random.rand(num_points, 2)
    num_circle = np.sum(points[:,0] ** 2 + points[:,1] ** 2 <= 1)
    return num_circle * 4 / num_points
    

In [28]:
monte_carplo_pi(1000000)

np.float64(3.139828)

In [19]:
np.pi - monte_carplo_pi(100000000)

np.float64(4.877358979316071e-05)

In [33]:
X = np.random.rand(100, 3)
true_weights = np.random.rand(3, 1)
y = X @ true_weights + np.random.rand(100, 1) * 0.005
weights = np.linalg.inv(X.T @ X) @ X.T @ y

In [34]:
weights

array([[0.83650814],
       [0.2779369 ],
       [0.80280044]])

In [35]:
true_weights

array([[0.83541069],
       [0.27623082],
       [0.80155852]])

In [40]:
def kmean(X, k, max_iter = 100):
    centroids = X[np.random.choice(len(X), k, replace = False)]
    for _ in range(max_iter):
        dist = np.linalg.norm(X[:, None] - centroids, axis = 2)
        label = np.argmin(dist, axis = 1)

        new_centroids = np.array([X[label == i].mean(axis = 0) for i in range(k)])

        if np.allclose(centroids, new_centroids):
            break
        centroids = new_centroids
    return label, centroids

In [41]:
data = np.random.rand(300, 2)
labels, centers = kmean(data, 3)

In [46]:
labels

array([1, 1, 0, 1, 1, 0, 0, 2, 0, 0, 2, 1, 0, 2, 0, 2, 0, 1, 0, 0, 2, 1,
       1, 1, 2, 1, 1, 0, 2, 1, 0, 2, 2, 0, 1, 1, 1, 0, 0, 2, 0, 1, 1, 2,
       0, 2, 2, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 2, 2, 2, 2, 0, 2, 1, 0, 0,
       0, 1, 1, 0, 2, 2, 2, 0, 0, 2, 0, 2, 2, 2, 0, 2, 0, 2, 1, 2, 1, 0,
       1, 1, 0, 2, 1, 0, 2, 1, 2, 1, 0, 1, 2, 0, 1, 2, 2, 1, 1, 1, 2, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 2, 2, 1, 0, 1, 2, 1, 1, 1, 1, 1,
       2, 0, 0, 1, 2, 1, 0, 0, 1, 1, 2, 1, 0, 0, 1, 0, 0, 2, 2, 2, 0, 0,
       0, 2, 0, 1, 0, 1, 1, 1, 2, 1, 0, 1, 2, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 2,
       0, 1, 0, 2, 0, 0, 1, 1, 2, 2, 0, 1, 0, 0, 2, 0, 2, 2, 0, 2, 0, 1,
       0, 2, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 2, 2, 0, 1, 0, 1, 2, 1, 2,
       2, 1, 1, 0, 2, 2, 2, 2, 0, 0, 1, 1, 0, 0, 1, 0, 2, 2, 1, 0, 1, 2,
       0, 2, 0, 1, 0, 2, 2, 0, 2, 2, 1, 2, 2, 1, 0, 0, 0, 2, 1, 2, 0, 0,
       2, 1, 1, 1, 1, 2, 0, 1, 2, 0, 2, 0, 0, 0])

In [47]:
centers

array([[0.46649556, 0.20554428],
       [0.75876956, 0.7077055 ],
       [0.21689732, 0.74630912]])

In [108]:
def simpson_integral(f, a, b, n):
    Xi = np.linspace(a, b, n + 1)
    yi = f(Xi)
    
    K = np.ones(len(Xi))
    K[1::2] = 4
    K[2::2] = 2
    Kf = np.sum(K * yi)

    return (b - a) / (3 * n) * Kf
    

In [109]:
simpson_integral(lambda x: np.sin(x), 0, np.pi, 100000)

np.float64(2.0)