In [1]:
import numpy as np

In [2]:
np.random.seed(42)

In [3]:
def monte_carplo_pi(num_points):
    points = np.random.rand(num_points, 2)
    num_circle = np.sum(points[:,0] ** 2 + points[:,1] ** 2 <= 1)
    return num_circle * 4 / num_points
    

In [4]:
monte_carplo_pi(1000000)

np.float64(3.141688)

In [5]:
np.pi - monte_carplo_pi(100000000)

np.float64(-0.00020006641020708926)

In [6]:
X = np.random.rand(100, 3)
true_weights = np.random.rand(3, 1)
y = X @ true_weights + np.random.rand(100, 1) * 0.005
weights = np.linalg.inv(X.T @ X) @ X.T @ y

In [7]:
weights

array([[0.1694507 ],
       [0.76309584],
       [0.88081807]])

In [8]:
true_weights

array([[0.1680606 ],
       [0.76156993],
       [0.87950545]])

In [9]:
def kmean(X, k, max_iter = 100):
    centroids = X[np.random.choice(len(X), k, replace = False)]
    for _ in range(max_iter):
        dist = np.linalg.norm(X[:, None] - centroids, axis = 2)
        label = np.argmin(dist, axis = 1)

        new_centroids = np.array([X[label == i].mean(axis = 0) for i in range(k)])

        if np.allclose(centroids, new_centroids):
            break
        centroids = new_centroids
    return label, centroids

In [10]:
data = np.random.rand(300, 2)
labels, centers = kmean(data, 3)

In [11]:
labels

array([0, 2, 1, 0, 2, 1, 1, 1, 0, 0, 2, 0, 1, 0, 0, 2, 2, 0, 0, 1, 1, 0,
       2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 0, 0, 1, 2, 2, 2, 0, 1, 0, 2, 1, 0,
       2, 2, 2, 1, 0, 2, 1, 2, 1, 2, 0, 2, 2, 1, 0, 0, 0, 2, 0, 2, 0, 2,
       2, 2, 1, 0, 1, 1, 1, 1, 0, 2, 2, 1, 0, 2, 2, 1, 1, 1, 2, 2, 1, 2,
       2, 1, 0, 0, 1, 0, 1, 0, 0, 2, 0, 2, 1, 1, 1, 1, 2, 2, 0, 2, 0, 0,
       0, 0, 1, 1, 1, 2, 1, 0, 0, 1, 1, 1, 2, 0, 1, 0, 0, 2, 2, 1, 1, 1,
       2, 2, 1, 2, 0, 1, 2, 2, 2, 2, 2, 0, 1, 1, 2, 1, 2, 2, 2, 0, 0, 2,
       1, 2, 0, 0, 0, 0, 1, 2, 0, 1, 0, 0, 1, 2, 1, 2, 1, 0, 2, 0, 1, 0,
       0, 0, 0, 2, 2, 2, 1, 2, 0, 2, 2, 0, 0, 2, 0, 0, 1, 2, 0, 1, 2, 2,
       1, 2, 0, 1, 1, 1, 2, 1, 2, 0, 2, 0, 0, 0, 2, 1, 2, 1, 2, 0, 2, 2,
       1, 2, 1, 1, 2, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2,
       0, 1, 2, 2, 2, 2, 2, 1, 2, 0, 2, 0, 2, 2, 1, 2, 2, 2, 1, 1, 0, 1,
       2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 0, 1, 1, 2, 1, 1, 2,
       0, 0, 0, 0, 1, 2, 2, 1, 2, 1, 0, 2, 1, 1])

In [12]:
centers

array([[0.77061988, 0.74199055],
       [0.22935475, 0.64890332],
       [0.56194277, 0.22062068]])

In [13]:
def simpson_integral(f, a, b, n):
    Xi = np.linspace(a, b, n + 1)
    yi = f(Xi)
    
    K = np.ones(len(Xi))
    K[1::2] = 4
    K[2::2] = 2
    Kf = np.sum(K * yi)

    return (b - a) / (3 * n) * Kf
    

In [14]:
simpson_integral(lambda x: np.sin(x), 0, np.pi, 100000)

np.float64(2.0)

In [15]:
import numpy as np

def batch_norm_2d(x, gamma=1.0, beta=0.0, eps=1e-5):
    print(f"Вход: shape={x.shape}, dtype={x.dtype}")
    
    mean = np.mean(x, axis=0, keepdims=True)
    var = np.var(x, axis=0, keepdims=True)
    x_norm = (x - mean) / np.sqrt(var + eps)
    result = gamma * x_norm + beta
    
    print(f"Выход shape={result.shape}, dtype={result.dtype}")
    print(f"Mean shape: {mean.shape}, Var shape: {var.shape}")
    
    return result



In [16]:
batch_data = np.random.randn(32, 64).astype(np.float32)
normalized = batch_norm_2d(batch_data)

Вход: shape=(32, 64), dtype=float32
Выход shape=(32, 64), dtype=float32
Mean shape: (1, 64), Var shape: (1, 64)


In [17]:
batch_data

array([[ 1.68628025e+00,  2.01887131e+00,  5.01013935e-01, ...,
        -1.38139057e+00,  1.13234377e+00,  1.56873429e+00],
       [-3.00890625e-01, -7.59264588e-01,  4.39399838e-01, ...,
        -1.24030316e+00,  1.26323617e+00, -1.96150362e+00],
       [-4.46567118e-01,  1.35297167e+00,  1.28847432e+00, ...,
        -1.73260427e+00,  6.67548478e-01, -8.40709925e-01],
       ...,
       [ 8.67554247e-01, -3.08651049e-02, -1.55643868e+00, ...,
        -8.12932968e-01, -1.39896142e+00,  3.52125794e-01],
       [ 2.15596604e+00, -7.37241030e-01, -1.23156270e-03, ...,
        -4.66485202e-01,  2.09029794e+00,  7.22065032e-01],
       [ 1.13131130e+00,  1.36751902e+00, -5.10528088e-01, ...,
         1.20878674e-01,  1.33805585e+00, -1.24311185e+00]],
      shape=(32, 64), dtype=float32)

In [18]:
normalized

array([[ 1.7875988 ,  1.7266177 ,  0.7308614 , ..., -1.507184  ,
         1.1450047 ,  1.4923323 ],
       [-0.19132474, -0.5277432 ,  0.67169434, ..., -1.3294014 ,
         1.2869917 , -1.8518258 ],
       [-0.33639663,  1.1862632 ,  1.4870468 , ..., -1.9497445 ,
         0.64081264, -0.79010946],
       ...,
       [ 0.9722708 ,  0.06332768, -1.2448771 , ..., -0.7908771 ,
        -1.600858  ,  0.3398516 ],
       [ 2.2553353 , -0.5098719 ,  0.24856317, ..., -0.3543222 ,
         2.1841567 ,  0.6902913 ],
       [ 1.2349333 ,  1.1980679 , -0.24050604, ...,  0.38580835,
         1.3681533 , -1.1713006 ]], shape=(32, 64), dtype=float32)